/**
 * AirGradient Go — Storage Service
 *
 * Two-tier storage management for the Go product:
 *
 * - Temporary (chart data): PayloadCache with RtcPayloadCacheStorage backend.
 *   Survives deep sleep (RTC memory); lost on power-off. Ring-buffer
 *   semantics — oldest entry is overwritten when the buffer is full.
 *
 * - Persistent (route data): POSIX file I/O on an FATFS filesystem provided
 *   by NandStorage. Survives power-off. One binary file per tracking session;
 *   route files are stored at <mount_path>/routes/route_NNNNN.bin, where
 *   NNNNN is the 5-digit session ID (10000–99999).
 *
 * No independent task — all methods are called synchronously by the
 * orchestrator.
 *
 * AirGradient
 * https://airgradient.com
 *
 * CC BY-SA 4.0 Attribution-ShareAlike 4.0 International License
 */

#pragma once

#include "measures_types.h"
#include "nand_storage.h"
#include "services/payload_cache.h"
#include "types/gps_types.h"

#include <cstdint>
#include <cstdio>
#include <ctime>

// ---------------------------------------------------------------------------
// RoutePoint
// ---------------------------------------------------------------------------

/// A single data point in a route log, combining GPS and sensor data with a
/// timestamp.  Written sequentially to a binary route file — no header, no
/// framing.  Fixed size allows O(1) seeks to the Nth point.
struct RoutePoint {
  time_t timestamp;      ///< System time at this point (synced from GPS)
  GpsData gps;           ///< GPS position and fix metadata
  MeasuresBasic sensors; ///< Sensor readings at this point
};

// ---------------------------------------------------------------------------
// CacheField
// ---------------------------------------------------------------------------

/// Identifies a single measurable field within MeasuresBasic.
/// Used with StorageService::read_cached_field() to retrieve the full
/// history of one field across all cached entries.
enum class CacheField : uint8_t {
  Temperature, ///< TempHumData::temperature (°C)
  Humidity,    ///< TempHumData::humidity (%)
  PM01,        ///< PMData::pm_01 — atmospheric PM1.0 (µg/m³)
  PM25,        ///< PMData::pm_25 — atmospheric PM2.5 (µg/m³)
  PM10,        ///< PMData::pm_10 — atmospheric PM10  (µg/m³)
  CO2,         ///< CO2Data::co2 (ppm, cast to float)
  TvocIndex,   ///< TVOCNOxData::tvoc_index (cast to float)
  NoxIndex,    ///< TVOCNOxData::nox_index  (cast to float)
};

// ---------------------------------------------------------------------------
// StorageService
// ---------------------------------------------------------------------------

class StorageService {
public:
  StorageService(PayloadCache &cache, NandStorage &nand);

  /// Mount NAND and scan for existing route files.  Call once during
  /// initialization.  PayloadCache::restore() should be called separately
  /// before this if RTC data needs to be recovered after deep sleep.
  ///
  /// Returns false if NAND mount fails.  Temporary cache still works
  /// independently of this return value.
  bool init();

  // --- Temporary (chart) operations ---

  /// Push a measurement into the temporary chart cache.
  /// Overwrites the oldest entry when the cache is full.
  void cache_measurement(const MeasuresBasic &m);

  /// Read the full history for one measurement field, oldest-first.
  ///
  /// Iterates all cached entries and extracts the value for @p field from
  /// each.  Invalid readings (per the field's own validator) are written as
  /// the corresponding MeasuresInvalid sentinel so the caller can identify
  /// and skip them during rendering.
  ///
  /// @param field      Which field to extract.
  /// @param out        Caller-owned buffer; must hold at least @p max_count
  ///                   floats.
  /// @param max_count  Capacity of @p out[].
  /// @return           Number of values written
  ///                   (= min(cached_count(), max_count)).
  uint16_t read_cached_field(CacheField field, float *out, uint16_t max_count) const;

  /// Number of cached measurements currently held in the ring buffer.
  uint16_t cached_count() const;

  /// Backup the cache ring buffer to RTC memory.  Call before deep sleep.
  void backup_cache() const;

  /// Restore the cache ring buffer from RTC memory.  Call after deep sleep
  /// wake, before init().
  void restore_cache();

  // --- Persistent (route) operations ---

  /// Start or resume a route tracking session.
  ///
  /// - If no file for @p session_id exists, creates a new one (write mode).
  /// - If a file already exists (e.g. resuming after deep sleep), opens it in
  ///   append mode and restores _current_point_count from the file size.
  ///
  /// @param session_id  5-digit session ID generated by the orchestrator
  ///                    (range 10000–99999).  Must be non-zero.
  ///
  /// Returns false if NAND is not mounted, the directory cannot be created,
  /// or the file cannot be opened.
  bool start_route(uint32_t session_id);

  /// Append one data point to the current route file.
  /// Returns false if no route is active or the write fails.
  bool append_route_point(const RoutePoint &point);

  /// Finish the current route tracking session.  Flushes and closes the
  /// route file.  Safe to call when no route is active (no-op).
  void end_route();

  /// Returns true if a route file is currently open.
  bool is_route_active() const;

  /// Number of points written to the currently open route file.
  /// Returns 0 when no route is active.
  uint32_t current_route_point_count() const;

private:
  PayloadCache &_cache;
  NandStorage &_nand;

  FILE *_route_file = nullptr;
  uint32_t _current_session_id = 0;
  uint32_t _current_point_count = 0;

  /// Ensure the <mount_path>/routes/ directory exists, creating it if needed.
  /// Returns false if NAND is not mounted or directory creation fails.
  bool ensure_route_dir() const;
};
