/**
 * AirGradient Go -- LP Core Watchdog Implementation
 *
 * Loads the LP Core binary blob, switches GPIO2 to RTCIO mode for LP
 * Core access, and provides start/stop for safe handoff between the LP
 * Core and main CPU.
 *
 * AirGradient
 * https://airgradient.com
 *
 * CC BY-SA 4.0 Attribution-ShareAlike 4.0 International License
 */

#include "go_ulp.h"

#include <driver/rtc_io.h>
#include <ulp_lp_core.h>

#include "board_config.h"
#include "rtos.h"

// Symbols generated by ulp_embed_binary()
extern const uint8_t ulp_wdt_bin_start[] asm("_binary_ulp_wdt_bin_start");
extern const uint8_t ulp_wdt_bin_end[] asm("_binary_ulp_wdt_bin_end");

static constexpr uint64_t ULP_WDT_INTERVAL_US = 60'000'000; // 60 s

void ulp_wdt_start() {
  ulp_lp_core_load_binary(ulp_wdt_bin_start,
                          static_cast<uint32_t>(ulp_wdt_bin_end - ulp_wdt_bin_start));

  // Switch GPIO2 to RTCIO mode so LP Core can drive it
  rtc_gpio_init(PIN_EXT_WDT);

  ulp_lp_core_cfg_t cfg = {
      .wakeup_source = ULP_LP_CORE_WAKEUP_SOURCE_LP_TIMER,
      .lp_timer_sleep_duration_us = ULP_WDT_INTERVAL_US,
  };
  ulp_lp_core_run(&cfg);
}

void ulp_wdt_stop() {
  // Allow any in-progress watchdog pulse to complete (~20 ms) before
  // stopping.  After deep sleep wake the LP Core is not executing, so
  // this is a no-op safety margin.
  RTOS::delay_ms(20);
  ulp_lp_core_stop();
}
