idf_component_register(
    SRCS "main.cpp"
         "reference_settings.cpp"
         "test_airgradient_client.cpp"
         "test_config.cpp"
         "test_gpio.cpp"
         "test_nand_storage.cpp"
         "test_payload_cache.cpp"
         "test_sensors.cpp"
         "test_serial.cpp"
         "test_touch.cpp"
         "test_ble.cpp"
    INCLUDE_DIRS "."
    REQUIRES
             airgradient-bms
             airgradient-client
             airgradient-common
             airgradient-config
             airgradient-gpio
             airgradient-nand-storage
             airgradient-payload-cache
             airgradient-sensors
             airgradient-serial
             airgradient-touch
             airgradient-ble
             esp_driver_gpio
             esp_driver_i2c
             esp_driver_spi
             esp_event
             esp_netif
             esp_wifi
             nvs_flash
)
